[build]
  base = "client"
  command = "npm run build && cd ../server && npm run build"
  publish = "dist"
  functions = "../dist/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]
